steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'europe-west1-docker.pkg.dev/buddy-demo-498822/cloud-run-source-deploy/buddy/buddy-backedn:$COMMIT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

images:
  - 'europe-west1-docker.pkg.dev/buddy-demo-498822/cloud-run-source-deploy/buddy/buddy-backedn:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
