steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'europe-west1-docker.pkg.dev/buddy-demo-498822/cloud-run-source-deploy/buddy/buddy-backedn:$COMMIT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-west1-docker.pkg.dev/buddy-demo-498822/cloud-run-source-deploy/buddy/buddy-backedn:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - buddy-backedn
      - '--platform=managed'
      - '--image=europe-west1-docker.pkg.dev/buddy-demo-498822/cloud-run-source-deploy/buddy/buddy-backedn:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--quiet'

images:
  - 'europe-west1-docker.pkg.dev/buddy-demo-498822/cloud-run-source-deploy/buddy/buddy-backedn:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
